app:
  name: bg-jug-site
  description: "The Bulgarian JUG Website"
  version: "0.0.1"

api:
  version: v1
  prefix: /api/${api.version}

authentication:
  key: "d3b6681900dd39068483c3a0decad73fbe42acb363fb55babb87a74b22d6aac5"
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 2592000
  users:
    - user: "user"
      name: "Regular user"
      password: "$2a$10$lSPgvAPfxWNLbXoMqQpkZe5jlxdtsQArfIwwnQYWsZFt7lZvPd0QS"
      enabled: true
    - user: "mitia"
      name: "Mitia user"
      password: "$2a$10$lSPgvAPfxWNLbXoMqQpkZe5jlxdtsQArfIwwnQYWsZFt7lZvPd0QS"
      enabled: true

spring:
  application.name: ${app.name}
  output.ansi.enabled: always

server:
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 8192
    mime-types:
      - application/json
      - text/html
      - text/css
      - application/javascript

management.security.enabled: false
